import type { DocumentTemplate } from '../types.js';

/**
 * 完整技术文档模板
 */
export const completeTemplate: DocumentTemplate = {
  id: 'complete_tech_doc_v1',
  name: '完整技术文档',
  type: 'complete',
  description: '包含架构、API、数据库、UI、测试等所有方面的完整技术文档',
  sections: [
    {
      id: 'project_overview',
      title: '项目概述',
      order: 1,
      required: true,
      contentType: 'text',
      aiPrompt: '基于 Spec 数据生成项目概述，包括项目背景、核心目标、技术选型等',
      subsections: [
        {
          id: 'project_background',
          title: '项目背景',
          order: 1,
          contentType: 'text',
          aiPrompt: '描述项目的业务背景和需求来源',
        },
        {
          id: 'core_objectives',
          title: '核心目标',
          order: 2,
          contentType: 'list',
          aiPrompt: '列出项目的核心目标和预期成果',
        },
        {
          id: 'tech_stack',
          title: '技术选型',
          order: 3,
          contentType: 'table',
          aiPrompt: '整理项目使用的技术栈和工具',
        },
      ],
    },
    {
      id: 'system_architecture',
      title: '系统架构',
      order: 2,
      required: true,
      contentType: 'diagram',
      aiPrompt: '基于实施计划生成系统架构设计，包括整体架构图、组件设计、数据流图',
      subsections: [
        {
          id: 'overall_architecture',
          title: '整体架构图',
          order: 1,
          contentType: 'diagram',
          aiPrompt: '生成系统整体架构图的描述',
        },
        {
          id: 'component_design',
          title: '组件设计',
          order: 2,
          contentType: 'text',
          aiPrompt: '详细描述各个组件的职责和交互关系',
        },
        {
          id: 'data_flow',
          title: '数据流图',
          order: 3,
          contentType: 'diagram',
          aiPrompt: '描述系统中的数据流向和处理过程',
        },
      ],
    },
    {
      id: 'api_design',
      title: 'API 设计',
      order: 3,
      required: true,
      contentType: 'code',
      aiPrompt: '基于执行记录生成 API 设计文档，包括接口规范、数据模型、错误处理',
      subsections: [
        {
          id: 'api_specification',
          title: '接口规范',
          order: 1,
          contentType: 'code',
          aiPrompt: '生成详细的 API 接口规范',
        },
        {
          id: 'data_models',
          title: '数据模型',
          order: 2,
          contentType: 'code',
          aiPrompt: '定义 API 使用的数据模型和结构',
        },
        {
          id: 'error_handling',
          title: '错误处理',
          order: 3,
          contentType: 'table',
          aiPrompt: '整理 API 的错误码和处理机制',
        },
      ],
    },
    {
      id: 'database_design',
      title: '数据库设计',
      order: 4,
      required: true,
      contentType: 'code',
      aiPrompt: '基于数据需求生成数据库设计，包括表结构、索引策略、数据迁移',
      subsections: [
        {
          id: 'table_structure',
          title: '表结构设计',
          order: 1,
          contentType: 'code',
          aiPrompt: '设计数据库表结构和字段定义',
        },
        {
          id: 'index_strategy',
          title: '索引策略',
          order: 2,
          contentType: 'text',
          aiPrompt: '制定数据库索引策略和优化方案',
        },
        {
          id: 'data_migration',
          title: '数据迁移',
          order: 3,
          contentType: 'code',
          aiPrompt: '设计数据迁移脚本和策略',
        },
      ],
    },
    {
      id: 'security_design',
      title: '安全设计',
      order: 5,
      required: true,
      contentType: 'text',
      aiPrompt: '设计系统安全方案，包括认证机制、权限控制、数据加密',
      subsections: [
        {
          id: 'authentication',
          title: '认证机制',
          order: 1,
          contentType: 'text',
          aiPrompt: '设计用户认证和授权机制',
        },
        {
          id: 'authorization',
          title: '权限控制',
          order: 2,
          contentType: 'text',
          aiPrompt: '设计角色权限和访问控制策略',
        },
        {
          id: 'data_encryption',
          title: '数据加密',
          order: 3,
          contentType: 'text',
          aiPrompt: '设计数据加密和安全传输方案',
        },
      ],
    },
    {
      id: 'ui_design',
      title: '用户界面设计',
      order: 6,
      required: false,
      contentType: 'text',
      aiPrompt: '设计用户界面和交互体验，包括页面结构、交互流程、样式规范',
      subsections: [
        {
          id: 'page_structure',
          title: '页面结构',
          order: 1,
          contentType: 'text',
          aiPrompt: '设计主要页面的结构和布局',
        },
        {
          id: 'interaction_flow',
          title: '交互流程',
          order: 2,
          contentType: 'diagram',
          aiPrompt: '设计用户交互流程和页面跳转',
        },
        {
          id: 'style_guide',
          title: '样式规范',
          order: 3,
          contentType: 'text',
          aiPrompt: '制定UI样式规范和设计系统',
        },
      ],
    },
    {
      id: 'testing_strategy',
      title: '测试策略',
      order: 7,
      required: true,
      contentType: 'text',
      aiPrompt: '制定测试策略和计划，包括单元测试、集成测试、端到端测试',
      subsections: [
        {
          id: 'unit_testing',
          title: '单元测试',
          order: 1,
          contentType: 'text',
          aiPrompt: '设计单元测试策略和覆盖率要求',
        },
        {
          id: 'integration_testing',
          title: '集成测试',
          order: 2,
          contentType: 'text',
          aiPrompt: '设计集成测试方案和测试用例',
        },
        {
          id: 'e2e_testing',
          title: '端到端测试',
          order: 3,
          contentType: 'text',
          aiPrompt: '设计端到端测试场景和自动化方案',
        },
      ],
    },
    {
      id: 'deployment_plan',
      title: '部署方案',
      order: 8,
      required: true,
      contentType: 'text',
      aiPrompt: '设计部署方案和运维策略，包括环境配置、监控告警、扩容策略',
      subsections: [
        {
          id: 'environment_config',
          title: '环境配置',
          order: 1,
          contentType: 'code',
          aiPrompt: '设计开发、测试、生产环境配置',
        },
        {
          id: 'monitoring_alerting',
          title: '监控告警',
          order: 2,
          contentType: 'text',
          aiPrompt: '设计系统监控和告警机制',
        },
        {
          id: 'scaling_strategy',
          title: '扩容策略',
          order: 3,
          contentType: 'text',
          aiPrompt: '设计系统扩容和负载均衡策略',
        },
      ],
    },
    {
      id: 'maintenance_guide',
      title: '维护指南',
      order: 9,
      required: false,
      contentType: 'text',
      aiPrompt: '编写系统维护指南，包括常见问题、故障排查、更新流程',
      subsections: [
        {
          id: 'troubleshooting',
          title: '故障排查',
          order: 1,
          contentType: 'text',
          aiPrompt: '整理常见问题和故障排查方法',
        },
        {
          id: 'update_process',
          title: '更新流程',
          order: 2,
          contentType: 'text',
          aiPrompt: '制定系统更新和发布流程',
        },
        {
          id: 'backup_recovery',
          title: '备份恢复',
          order: 3,
          contentType: 'text',
          aiPrompt: '设计数据备份和灾难恢复方案',
        },
      ],
    },
  ],
  metadata: {
    version: '1.0.0',
    author: 'AI Document Generator',
    createdAt: new Date('2024-01-01'),
    tags: ['complete', 'technical', 'comprehensive'],
    estimatedGenerationTime: 300, // 5 分钟
  },
};
